
#define PLAYER_COLLISION_BITMASK  1
#define WALL_COLLISION_BITMASK 2
#define MOVE_NORTH 11
#define MOVE_EAST 12
#define MOVE_SOUTH 13
#define MOVE_WEST 14
#define TILE_SPACE 110
#define ENEMY_CHANGEDIRECTION_TAG 201